# Generated by Django 5.1 on 2024-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='Артикул'),
        ),
    ]
