# Generated by Django 5.1 on 2024-08-27 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productmodel_sku'),
        ('vending_machines', '0002_alter_vendingmachinemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата затаривания')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vending_machines.vendingmachinemodel', verbose_name='Торговый автомат')),
            ],
            options={
                'verbose_name': 'История затаривания',
                'verbose_name_plural': 'Истории затаривания',
                'db_table': 'packing__packing',
            },
        ),
        migrations.CreateModel(
            name='PackingAddedItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productmodel', verbose_name='Товар')),
                ('packing_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='packing.packingmodel')),
            ],
            options={
                'verbose_name': 'Загруженные продукты',
                'db_table': 'packing__packing_added_item',
            },
        ),
        migrations.CreateModel(
            name='PackingRemovedItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('packing_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_items', to='packing.packingmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Загруженные продукты',
                'db_table': 'packing__packing_removed_item',
            },
        ),
    ]
