# Generated by Django 5.1 on 2024-08-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_rename_packing_history_packingremoveditemmodel_packing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingaddeditemmodel',
            old_name='packing_history',
            new_name='packing',
        ),
    ]
