# Generated by Django 5.1 on 2024-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_rename_packing_history_packingaddeditemmodel_packing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingaddeditemmodel',
            options={'verbose_name': 'Загруженный продукт', 'verbose_name_plural': 'Загруженные продукты'},
        ),
        migrations.AlterModelOptions(
            name='packingremoveditemmodel',
            options={'verbose_name': 'Выгруженный продукт', 'verbose_name_plural': 'Выгруженные продукты'},
        ),
    ]
