# Generated by Django 5.1 on 2024-09-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_alter_packingaddeditemmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingaddeditemmodel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='packingremoveditemmodel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
