# Generated by Django 5.1 on 2024-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_packingaddeditemmodel_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingaddeditemmodel',
            name='expiration_date',
            field=models.DurationField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='packingremoveditemmodel',
            name='expiration_date',
            field=models.DurationField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
