services:
  # Backend
  server:
    container_name: server
    hostname: server
    restart: always
    build:
      context: ./server
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./server/.env
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
