services:
  # Backend
  server:
    container_name: server
    hostname: server
    restart: always
    build:
      context: ./server
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./server/.env
    networks:
      - backbone

  # Frontend
  client:
    container_name: client
    hostname: client
    restart: always
    build:
      context: ./client
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
     - server
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
