# Generated by Django 5.0.6 on 2024-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cell',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ячейка'),
        ),
    ]
