# Generated by Django 5.0.6 on 2024-08-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productmodel_cell_productmodel_cells_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cells',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='max_count',
        ),
        migrations.CreateModel(
            name='CellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('max_count', models.IntegerField(default=10, verbose_name='Максимальное количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'db_table': 'products__cells',
            },
        ),
    ]
