# Generated by Django 5.0.6 on 2024-08-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_cellmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmodel',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер ячейки'),
        ),
        migrations.AlterField(
            model_name='cellmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
