# Generated by Django 5.0.6 on 2024-08-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cellmodel_number_alter_cellmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_empty',
            field=models.BooleanField(default=True, verbose_name='Пусто?'),
        ),
    ]
