# Generated by Django 5.0.6 on 2024-08-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productmodel_is_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='is_empty',
        ),
    ]
