# Generated by Django 5.1 on 2024-08-26 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productmodel_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок годности')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.cellmodel', verbose_name='Ячейка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в ячейке',
                'verbose_name_plural': 'Товары в ячейках',
                'db_table': 'products__product_details',
            },
        ),
    ]
