# Generated by Django 5.1 on 2024-08-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productdetailmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetailModel',
            new_name='ProductInCellModel',
        ),
        migrations.AlterField(
            model_name='cellmodel',
            name='count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество'),
        ),
    ]
