# Generated by Django 5.1 on 2024-08-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_productdetailmodel_productincellmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincellmodel',
            name='expiration_date',
            field=models.DurationField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
