# Generated by Django 5.1 on 2024-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productincellmodel_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincellmodel',
            name='product',
        ),
        migrations.AlterField(
            model_name='cellmodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
