# Generated by Django 5.1 on 2024-08-27 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productincellmodel_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincellmodel',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 9, 3, 26, 851356, tzinfo=datetime.timezone.utc), verbose_name='Дата загрузки'),
        ),
    ]
