# Generated by Django 5.1 on 2024-08-27 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productincellmodel_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincellmodel',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
    ]
