# Generated by Django 5.1 on 2024-08-27 16:20

import api.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productincellmodel_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=api.products.models.category_image_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=api.products.models.product_image_upload_path, verbose_name='Изображение'),
        ),
    ]
