# Generated by Django 5.1 on 2024-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_categorymodel_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='sku',
            field=models.CharField(max_length=128, unique=True, verbose_name='Артикул'),
        ),
    ]
