# Generated by Django 5.1.3 on 2024-11-22 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название автомата')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес автомата')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='SKU')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Автомат',
                'verbose_name_plural': 'Автоматы',
            },
        ),
    ]
