# Generated by Django 5.1.3 on 2024-11-22 19:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('sku', models.CharField(max_length=128, unique=True, verbose_name='SKU')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MachineCellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер ячейки')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('max_count', models.IntegerField(verbose_name='Максимальное количество')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_sku', models.CharField(max_length=128, verbose_name='SKU товара')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='MachineOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(unique=True, verbose_name='ID заказа')),
                ('product_sku', models.CharField(max_length=128, verbose_name='Артикул товара')),
                ('amount', models.IntegerField(default=0, verbose_name='Стоимость в копейках')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='MachineProductInCellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.IntegerField(verbose_name='Номер ячейки')),
                ('upload_date', models.DateField(verbose_name='Дата загрузки')),
                ('expiration_date', models.DurationField(blank=True, null=True, verbose_name='Срок годности')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel')),
            ],
            options={
                'verbose_name': 'Товар в ячейке',
                'verbose_name_plural': 'Товары в ячейках',
            },
        ),
        migrations.CreateModel(
            name='MachineProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('category_name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('category_sku', models.CharField(max_length=128, verbose_name='SKU категории')),
                ('expiration_date', models.DurationField(default=datetime.timedelta(0), verbose_name='Срок годности')),
                ('price', models.IntegerField(default=10000, verbose_name='Стоимость (в копейках)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
