# Generated by Django 5.1.3 on 2024-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0002_machinecategorymodel_machinecellmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecategorymodel',
            name='sku',
            field=models.CharField(max_length=128, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='sku',
            field=models.CharField(max_length=128, verbose_name='SKU'),
        ),
        migrations.AlterUniqueTogether(
            name='machinecategorymodel',
            unique_together={('machine', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='machinecellmodel',
            unique_together={('machine', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='machineproductmodel',
            unique_together={('machine', 'sku')},
        ),
    ]
