# Generated by Django 5.1.3 on 2024-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0003_alter_machinecategorymodel_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinecellmodel',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='machineproductmodel',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='order_id',
            field=models.UUIDField(verbose_name='ID заказа'),
        ),
        migrations.AlterUniqueTogether(
            name='machineordermodel',
            unique_together={('machine', 'order_id')},
        ),
    ]
