# Generated by Django 5.1.3 on 2024-11-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0004_remove_machinecellmodel_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineproductincellmodel',
            name='product_in_cell_id',
            field=models.IntegerField(default=-1, verbose_name='ID записи в автомате'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='machineproductincellmodel',
            unique_together={('machine', 'product_in_cell_id')},
        ),
    ]
