# Generated by Django 5.1.3 on 2024-11-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0005_machineproductincellmodel_product_in_cell_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineproductincellmodel',
            name='upload_date',
            field=models.DateTimeField(verbose_name='Дата загрузки'),
        ),
    ]
