# Generated by Django 5.1.3 on 2024-11-23 02:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer', '0006_alter_machineproductincellmodel_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecategorymodel',
            name='machine',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machinecategorymodel',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='machinecategorymodel',
            name='sku',
            field=models.CharField(editable=False, max_length=128, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='machinecellmodel',
            name='count',
            field=models.IntegerField(editable=False, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='machinecellmodel',
            name='machine',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machinecellmodel',
            name='max_count',
            field=models.IntegerField(editable=False, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='machinecellmodel',
            name='number',
            field=models.IntegerField(editable=False, verbose_name='Номер ячейки'),
        ),
        migrations.AlterField(
            model_name='machinecellmodel',
            name='product_sku',
            field=models.CharField(editable=False, max_length=128, verbose_name='SKU товара'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='address',
            field=models.CharField(editable=False, max_length=255, verbose_name='Адрес автомата'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Название автомата'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='sku',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='amount',
            field=models.IntegerField(default=0, editable=False, verbose_name='Стоимость в копейках'),
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='is_paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='Оплачено?'),
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='machine',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='order_id',
            field=models.UUIDField(editable=False, verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='machineordermodel',
            name='product_sku',
            field=models.CharField(editable=False, max_length=128, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='machineproductincellmodel',
            name='cell_number',
            field=models.IntegerField(editable=False, verbose_name='Номер ячейки'),
        ),
        migrations.AlterField(
            model_name='machineproductincellmodel',
            name='expiration_date',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='machineproductincellmodel',
            name='machine',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machineproductincellmodel',
            name='product_in_cell_id',
            field=models.IntegerField(editable=False, verbose_name='ID записи в автомате'),
        ),
        migrations.AlterField(
            model_name='machineproductincellmodel',
            name='upload_date',
            field=models.DateTimeField(editable=False, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='category_sku',
            field=models.CharField(editable=False, max_length=128, verbose_name='SKU категории'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='composition',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='description',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='expiration_date',
            field=models.DurationField(default=datetime.timedelta(0), editable=False, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='machine',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='synchronizer.machinemodel'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='price',
            field=models.IntegerField(default=0, editable=False, verbose_name='Стоимость (в копейках)'),
        ),
        migrations.AlterField(
            model_name='machineproductmodel',
            name='sku',
            field=models.CharField(editable=False, max_length=128, verbose_name='SKU'),
        ),
    ]
