# Generated by Django 5.0.6 on 2024-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='max_count',
            field=models.IntegerField(default=10, verbose_name='Максимальное количество'),
        ),
    ]
