# Generated by Django 5.0.6 on 2024-08-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_count_productmodel_max_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cell',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cells',
            field=models.TextField(default='[]', verbose_name='Ячейки (в json)'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='max_count',
            field=models.IntegerField(default=10, verbose_name='Максимальное количество для ячейки'),
        ),
    ]
