# Generated by Django 5.0.6 on 2024-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productmodel_cells_remove_productmodel_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
