# Generated by Django 5.1 on 2024-08-26 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_is_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='expiration_date',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Срок годности'),
        ),
    ]
