# Generated by Django 5.1 on 2024-08-27 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productincellmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincellmodel',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 9, 2, 47, 803259, tzinfo=datetime.timezone.utc), verbose_name='Дата загрузки'),
        ),
    ]
