# Generated by Django 5.1.3 on 2024-11-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productmodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
