# Generated by Django 5.1.3 on 2024-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_categorymodel_is_new_categorymodel_is_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmodel',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cellmodel',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
