# Generated by Django 5.1.3 on 2024-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_cellmodel_is_new_cellmodel_is_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincellmodel',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productincellmodel',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
