# Generated by Django 5.1 on 2024-08-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingremoveditemmodel',
            old_name='packing_history',
            new_name='packing',
        ),
    ]
