# Generated by Django 5.0.6 on 2024-05-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentModel',
        ),
        migrations.RenameModel(
            old_name='ReceiptItem',
            new_name='ReceiptItemModel',
        ),
        migrations.RenameModel(
            old_name='Receipt',
            new_name='ReceiptModel',
        ),
    ]
