# Generated by Django 5.0.6 on 2024-05-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_receiptitemmodel_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='payment_fail',
        ),
        migrations.RemoveField(
            model_name='receiptmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receiptmodel',
            name='phone',
        ),
    ]
