# Generated by Django 5.0.6 on 2024-05-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_paymentmodel_payment_fail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitemmodel',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptitems', to='payment.receiptmodel', verbose_name='Чек'),
        ),
    ]
