# Generated by Django 5.0.6 on 2024-05-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_receiptitemmodel_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='email',
            field=models.CharField(default='user@example.com', max_length=64, verbose_name='Электронный адрес для отправки чека покупателю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон покупателя'),
        ),
        migrations.AlterField(
            model_name='receiptitemmodel',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptitem', to='payment.receiptmodel', verbose_name='Чек'),
        ),
    ]
