# Generated by Django 5.1 on 2024-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='sku',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
