# Generated by Django 5.1 on 2024-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendingMachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('last_sync_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
            options={
                'verbose_name': 'Автомат',
                'verbose_name_plural': 'Автоматы',
                'db_table': 'vending_machines__vending_machine',
            },
        ),
    ]
