# Generated by Django 5.1 on 2024-08-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachinemodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=8),
        ),
    ]
