# Generated by Django 5.1 on 2024-08-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField(default=0)),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='core.vendingmachinemodel')),
            ],
            options={
                'verbose_name': 'Товарный остаток',
                'verbose_name_plural': 'Товарные остатки',
                'db_table': 'products_stock',
            },
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=200)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_syncs', to='core.vendingmachinemodel')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales',
            },
        ),
    ]
