# Generated by Django 5.1 on 2024-08-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='order_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
