# Generated by Django 5.1 on 2024-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_alter_salesmodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
