# Generated by Django 5.1 on 2024-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_salesmodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
