# Generated by Django 5.1.3 on 2024-11-22 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizerTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Токен сервиса синхронизации',
                'verbose_name_plural': 'Токены сервиса синхронизации',
            },
        ),
    ]
