# Generated by Django 5.1.3 on 2024-11-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_ordermodel_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
