# Generated by Django 5.1.3 on 2024-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermodel_is_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
