# Generated by Django 5.0.6 on 2024-08-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_paid_at_alter_ordermodel_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='paid_at',
        ),
    ]
